S3 Block Public Access Fix
jenkins-x/terraform-aws-eks-jx pull request #362
Opened 2023-04-26 21:01 UTC by tgelpi

#### Description

#### Special notes for the reviewer(s)

#### Which issue this PR fixes

fixes #

#### Release notes

2023-04-28 23:22 UTC, awisky approved these changes

2023-05-25 14:53 UTC, msvticket requested changes
With the changes made by AWS the sufficient and appropriate change is to simply remove the acl.

From reading https://github.com/hashicorp/terraform-provider-aws/issues/28353 my understanding is that the aws_s3_bucket_ownership_controls resource is needed together with aws_s3_bucket_acl, not otherwise. So the count expression of the aws_s3_bucket_ownership_controls resources are wrong. This also means that the descriptions of the enable_acl variables need to be corrected.

> 
> With the new default security settings, a private ACL definition can likely be removed completely as the default security settings already ensure public access is restricted upon bucket creation.
> 
> However, if a private ACL is explicitly required, the following configuration splits bucket and ACL creation into separate API calls, with the requisite object ownership API call in between.

2023-05-25 14:53 UTC, msvticket commented on modules/cluster/storage.tf
> +  count  = var.enable_reports_storage && !var.enable_acl ? 1 : 0
```suggestion
  count  = var.enable_reports_storage && var.enable_acl ? 1 : 0
```

2023-05-25 14:53 UTC, msvticket commented on modules/cluster/storage.tf
> +  count  = var.enable_repository_storage && !var.enable_acl ? 1 : 0
```suggestion
  count  = var.enable_repository_storage && var.enable_acl ? 1 : 0
```

2023-05-25 14:53 UTC, msvticket commented on modules/vault/main.tf
> +  count  = local.create_vault_resources && !var.enable_acl ? 1 : 0
```suggestion
  count  = local.create_vault_resources && var.enable_acl ? 1 : 0
```

2023-05-25 14:53 UTC, msvticket commented on modules/cluster/storage.tf
> +  count  = var.enable_logs_storage && !var.enable_acl ? 1 : 0
```suggestion
  count  = var.enable_logs_storage && var.enable_acl ? 1 : 0
```

2023-05-25 14:53 UTC, msvticket commented on modules/backup/main.tf
> +  count  = var.enable_backup && !var.enable_acl ? 1 : 0
```suggestion
  count  = var.enable_backup && var.enable_acl ? 1 : 0
```

2023-06-26 10:13 UTC, msvticket approved these changes

2023-06-26 10:15 UTC, merged